### ISSUE TITLE
Öneri

### ISSUE THREAD

**Issue by grkmefedrsn34** [1Thoran/50-Days-Of-Javascirpt#1]
Bence  javascript konusunda tam anlamıyla öğrenmek açısından mantıklı çünkü Türkiye'de sektör tamamen javascript  üzerine kurulu bunun dışında eğer web master veya web dev olarak devam edeceksen MERN ile devam etmeni öneririm kankam

**Comment by grkmefedrsn34** [comment]
ve bol bol proje yapmayıda ihmal etme

**Comment by ahmet4k** [comment]
Eyvallah kankam çok sağolasın
